#! /usr/bin/zsh
mkdir out;
for ((i = 1; i < 4; i++)); do python3 DND/DNDCompiler.py in/0"$i"_syntax_err.dnd out/0"$i"; done
for ((i = 4; i < 8; i++)); do python3 DND/DNDCompiler.py in/0"$i"_semantic_err.dnd out/0"$i"; done
for ((i = 8; i < 10; i++)); do python3 DND/DNDCompiler.py in/0"$i"_use_case.dnd out/0"$i"; done
